# Generated by Django 4.2.24 on 2025-09-29 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authenticationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.TextField(max_length=500)),
                ('project_imageone', models.ImageField(upload_to='project_images/')),
                ('project_imagetwo', models.ImageField(upload_to='project_images/')),
                ('project_imagethree', models.ImageField(upload_to='project_images/')),
                ('project_link', models.URLField(blank=True)),
                ('skillsone', models.CharField(max_length=200)),
                ('skill_descriptionone', models.TextField(max_length=500)),
                ('skillstwo', models.CharField(max_length=200)),
                ('skill_descriptiontwo', models.TextField(max_length=500)),
                ('skillsthree', models.CharField(max_length=200)),
                ('skill_descriptionthree', models.TextField(max_length=500)),
                ('skillsfour', models.CharField(max_length=200)),
                ('skill_descriptionfour', models.TextField(max_length=500)),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('experience_description', models.TextField(max_length=500)),
                ('institution', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('course_duration', models.CharField(max_length=50)),
                ('education_description', models.TextField(max_length=500)),
                ('certification_name', models.CharField(max_length=100)),
                ('issuing_institution', models.CharField(max_length=100)),
                ('certification_year', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticationapp.profile')),
            ],
        ),
    ]
